"""make category slug nullable

Revision ID: 5ddce1d4cc9b
Revises: b2c3d4e5f6a7
Create Date: 2026-08-26 16:58:12.204093
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ddce1d4cc9b'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_items_short_code'), 'items', type_='unique')
    op.drop_index(op.f('ix_items_short_code'), table_name='items')
    op.create_index(op.f('ix_items_short_code'), 'items', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_short_code'), table_name='items')
    op.create_index(op.f('ix_items_short_code'), 'items', ['short_code'], unique=False)
    op.create_unique_constraint(op.f('uq_items_short_code'), 'items', ['short_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
