"""make category slug nullable

Revision ID: 5ddce1d4cc9b
Revises: b2c3d4e5f6a7
Create Date: 2026-08-26 16:58:12.204093
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ddce1d4cc9b'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories') as batch_op:
        batch_op.alter_column('slug', existing_type=sa.VARCHAR(), nullable=True)
    with op.batch_alter_table('items') as batch_op:
        batch_op.drop_constraint(op.f('uq_items_short_code'), type_='unique')
        batch_op.drop_index(op.f('ix_items_short_code'))
        batch_op.create_index(op.f('ix_items_short_code'), ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items') as batch_op:
        batch_op.drop_index(op.f('ix_items_short_code'))
        batch_op.create_index(op.f('ix_items_short_code'), ['short_code'], unique=False)
        batch_op.create_unique_constraint(op.f('uq_items_short_code'), ['short_code'])
    with op.batch_alter_table('categories') as batch_op:
        batch_op.alter_column('slug', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
