"""initial schema

Revision ID: 6a46111dc73e
Revises: 
Create Date: 2026-08-25 22:38:52.599314
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a46111dc73e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_scopes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_categories_parent_category_id', 'categories', ['parent_category_id'], unique=False)
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True)
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_parent_location_id', 'locations', ['parent_location_id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('supabase_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('supabase_id')
    )
    op.create_table('access_scope_permissions',
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['access_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_scope_permissions_scope_id', 'access_scope_permissions', ['scope_id'], unique=False)
    op.create_table('access_scope_rules',
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('rule_value', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['access_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_scope_rules_scope_id', 'access_scope_rules', ['scope_id'], unique=False)
    op.create_table('access_scope_users',
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['access_scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_scope_users_scope_id', 'access_scope_users', ['scope_id'], unique=False)
    op.create_index('ix_access_scope_users_user_id', 'access_scope_users', ['user_id'], unique=False)
    op.create_table('items',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('parent_item_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_category_id', 'items', ['category_id'], unique=False)
    op.create_index('ix_items_location_id', 'items', ['location_id'], unique=False)
    op.create_index('ix_items_name', 'items', ['name'], unique=False)
    op.create_index('ix_items_parent_item_id', 'items', ['parent_item_id'], unique=False)
    op.create_index('ix_items_serial_number', 'items', ['serial_number'], unique=False)
    op.create_index('ix_items_sku', 'items', ['sku'], unique=False)
    op.create_table('item_attributes',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_attributes_item_id', 'item_attributes', ['item_id'], unique=False)
    op.create_table('item_images',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_images_item_id', 'item_images', ['item_id'], unique=False)
    op.create_table('item_movements',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('moved_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_movements_item_id', 'item_movements', ['item_id'], unique=False)
    op.create_index('ix_item_movements_moved_at', 'item_movements', ['moved_at'], unique=False)
    op.create_table('item_relationships',
    sa.Column('source_item_id', sa.UUID(), nullable=False),
    sa.Column('target_item_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('source_item_id != target_item_id', name='ck_no_self_relationship'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_relationships_source', 'item_relationships', ['source_item_id'], unique=False)
    op.create_index('ix_item_relationships_target', 'item_relationships', ['target_item_id'], unique=False)
    op.create_table('item_tags',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_index('ix_item_tags_item_id', 'item_tags', ['item_id'], unique=False)
    op.create_index('ix_item_tags_tag_id', 'item_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_tags_tag_id', table_name='item_tags')
    op.drop_index('ix_item_tags_item_id', table_name='item_tags')
    op.drop_table('item_tags')
    op.drop_index('ix_item_relationships_target', table_name='item_relationships')
    op.drop_index('ix_item_relationships_source', table_name='item_relationships')
    op.drop_table('item_relationships')
    op.drop_index('ix_item_movements_moved_at', table_name='item_movements')
    op.drop_index('ix_item_movements_item_id', table_name='item_movements')
    op.drop_table('item_movements')
    op.drop_index('ix_item_images_item_id', table_name='item_images')
    op.drop_table('item_images')
    op.drop_index('ix_item_attributes_item_id', table_name='item_attributes')
    op.drop_table('item_attributes')
    op.drop_index('ix_items_sku', table_name='items')
    op.drop_index('ix_items_serial_number', table_name='items')
    op.drop_index('ix_items_parent_item_id', table_name='items')
    op.drop_index('ix_items_name', table_name='items')
    op.drop_index('ix_items_location_id', table_name='items')
    op.drop_index('ix_items_category_id', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_access_scope_users_user_id', table_name='access_scope_users')
    op.drop_index('ix_access_scope_users_scope_id', table_name='access_scope_users')
    op.drop_table('access_scope_users')
    op.drop_index('ix_access_scope_rules_scope_id', table_name='access_scope_rules')
    op.drop_table('access_scope_rules')
    op.drop_index('ix_access_scope_permissions_scope_id', table_name='access_scope_permissions')
    op.drop_table('access_scope_permissions')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index('ix_locations_parent_location_id', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_categories_slug', table_name='categories')
    op.drop_index('ix_categories_parent_category_id', table_name='categories')
    op.drop_table('categories')
    op.drop_table('access_scopes')
    # ### end Alembic commands ###
